require('./lib/logger');
require('./lib/configuration-loader');
require('./lib/track-application-files');
require('./lib/gather-modules-model');
require('./lib/create-modules-dependency-model');
require('./lib/topological-graph-sort-and-modules-resolve');
require('./lib/instantiate-modules');
require('./lib/klark-api');
require('./lib/klark');